### ISSUE TITLE
The word "addPaths" in the configuration file is incorrect

### ISSUE THREAD

**Issue by chinazj** [kubesphere/porter#108]
from porter/config/samples/network_v1alpha1_bgppeer.yaml

```
apiVersion: network.kubesphere.io/v1alpha1
kind: BgpPeer
metadata:
  name: bgppeer-sample
spec:
  # Add fields here
  config:
    peerAs : 65001
    neighborAddress: 192.168.0.6
  addAaths: ##this word should be addPaths
    sendMax: 10
```
