### ISSUE TITLE
visit external IP failed (Connetction refused) from unloaded node while service  externalTrafficPolicy=Local

### ISSUE THREAD

**Issue by Mrtao1028** [kubesphere/porter#188]
visit external IP failed (Connetction refused) from unloaded node while service  externalTrafficPolicy=Local

test workload assigend to `node3, node4`
connect from `node1,node2` get `Connect refused`
connect from `node3,node4` get `correct response`
connect from outside the cluser  get  `correct response`

test yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: porter-bgp-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: porter-bgp
  template:
    metadata:
      labels:
        app: porter-bgp
    spec:
      containers:
      - name: whoami
        image: hub.2980.com/dockerhub/containous/whoami
        ports:
        - name: web
          containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: porter-bgp-svc
  annotations:
    lb.kubesphere.io/v1alpha1: porter
    protocol.porter.kubesphere.io/v1alpha1: bgp
    eip.porter.kubesphere.io/v1alpha2: lb-eip-pool-10-17-140
spec:
  selector:
    app: porter-bgp
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
  externalTrafficPolicy: Local
```

env:
k8s version:1.17.9
os: debian 9
kernel version: 4.9.0

--------------------------------
it cause by `kube-porxy` set external ip on interface `kube-ipvs0` for every node. 
```bash
$  kubectl get svc
NAME             TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
kubernetes       ClusterIP      10.251.0.1       <none>        443/TCP        16d
porter-bgp-svc   LoadBalancer   10.251.130.228   10.17.140.0   80:30015/TCP   26m

$ ip a show kube-ipvs0
9: kube-ipvs0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default 
    link/ether 96:ae:80:2a:fd:f7 brd ff:ff:ff:ff:ff:ff
    ...
    inet 10.251.0.1/32 brd 10.251.0.1 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    ...
    inet 10.17.140.0/32 brd 10.17.140.0 scope global kube-ipvs0
       valid_lft forever preferred_lft forever

$ ip r get 10.17.140.0
local 10.17.140.0 dev lo src 10.17.140.0 
    cache <local> 
```
