### ISSUE TITLE
BGP router only learn one bgp route

### ISSUE THREAD

**Issue by Mrtao1028** [kubesphere/porter#191]
test service use EIP 10.17.140.0,  the pod assigned to two Node (10.17.64.109, 10.19.66.167), 
![image](https://user-images.githubusercontent.com/7741839/109387291-8ff28880-793b-11eb-81bd-506e13c7c336.png)
`porter-manager` can find 2 routes
![image](https://user-images.githubusercontent.com/7741839/109387331-d34cf700-793b-11eb-9bec-efdf257684ec.png)

but bgp neighbor only learn one route  `10.17.140.0 nexthop via 10.17.64.109`
![image](https://user-images.githubusercontent.com/7741839/109387304-a39def00-793b-11eb-86f9-6c1aed6c4bec.png)

I use gobgpd as test BGP Router
```yaml
global:
    config:
        as: 65109
        router-id: 10.17.67.50
neighbors:
    - config:
        neighbor-address: 10.17.66.167
        peer-as: 65053
```
i expect BGP Router learn to route
![image](https://user-images.githubusercontent.com/7741839/109387463-92a1ad80-793c-11eb-83c2-35ac5df8da82.png)

env:
porter version: v0.4.1
k8s version: 1.17.9

**Comment by duanjiong** [comment]
You can follow the steps below to see if add-path is not enabled by checking the relevant configuration properties of neighbor
```
root@i-y0a0i550:~# kubectl exec -n porter-system  porter-manager-847f66dfc7-cl8nw  -ti /bin/sh
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
/ # gobgp neighbor
Peer          AS  Up/Down State       |#Received  Accepted
172.28.3.1 50003 00:19:05 Establ      |        0         0
/ # gobgp neighbor 172.28.3.1
BGP neighbor is 172.28.3.1, remote AS 50003
  BGP version 4, remote router ID 172.28.3.1
  BGP state = ESTABLISHED, up for 00:19:14
  BGP OutQ = 0, Flops = 0
  Hold time is 90, keepalive interval is 30 seconds
  Configured hold time is 90, keepalive interval is 30 seconds

  Neighbor capabilities:
    multiprotocol:
        ipv4-unicast:   advertised and received
        ipv6-unicast:   received
    route-refresh:      advertised and received
    extended-nexthop:   advertised
        Local:  nlri: ipv4-unicast, nexthop: ipv6
    graceful-restart:   received
    4-octet-as: advertised and received
    add-path:   advertised and received
      Local:
         ipv4-unicast:  send
      Remote:
         ipv4-unicast:  receive/send
         UnknownFamily(1174405191):     none
    enhanced-route-refresh:     received
    long-lived-graceful-restart:        received
  Message statistics:
                         Sent       Rcvd
    Opens:                  1          1
    Notifications:          0          0
    Updates:                0          1
    Keepalives:            39         44
    Route Refresh:          0          0
    Discarded:              0          0
    Total:                 40         46
  Route statistics:
    Advertised:             0
    Received:               0
    Accepted:               0
/ #
```

**Comment by duanjiong** [comment]
You can reference this doc https://github.com/osrg/gobgp/blob/master/docs/sources/add-paths.md

**Comment by Mrtao1028** [comment]
> You can reference this doc https://github.com/osrg/gobgp/blob/master/docs/sources/add-paths.md

3Q, 
enable `add-paths`  can learn  right routes
![image](https://user-images.githubusercontent.com/7741839/109459036-f50fc080-7a98-11eb-9717-690b3ab69174.png)

```yaml
global:
    config:
        as: 65109
        router-id: 10.17.67.50
neighbors:
    - config:
        neighbor-address: 10.17.66.167
        peer-as: 65053
      add-paths:
        config:
          receive: true
          send-max: 8
```
