### ISSUE TITLE
Assign IP to different services

### ISSUE THREAD

**Issue by driftavalli** [kubesphere/porter#52]
How does one select which EIP to assign to a service. It seems the first EIP gets assigned to the first service that comes online but subsequent service is stuck on pending for external IP despite creating a second EIP.

**Comment by magicsong** [comment]
you should specify another eip on the annotation of service or create a new eip to pool. 
Creating eip example:
```bash
kubectl apply -f - <<EOF
apiVersion: network.kubesphere.io/v1alpha1
kind: EIP
metadata:
    labels:
          controller-tools.k8s.io: "1.0"
name: eip-sample
spec:
# Add fields here
    address: 11.11.11.11 #replace eip here
    disable: false
EOF
```

**Comment by driftavalli** [comment]
I can't seem to get this working:

```
cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuard-deployment
  labels:
    app: kuard
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kuard
  template:
    metadata:
      labels:
        app: kuard
    spec:
      containers:
        - image: gcr.io/kuar-demo/kuard-amd64:1
          name: kuard
          ports:
            - containerPort: 8080
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: kuard-service
  annotations:
    lb.kubesphere.io/v1alpha1: porter
    controller-tools.k8s.io: "1.0"
spec:
  selector:
    app: kuard
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: network.kubesphere.io/v1alpha1
kind: EIP
metadata:
  labels:
      controller-tools.k8s.io: "1.0"
  name: eip-kuard
  namespace: porter-system
spec:
# Add fields here
  address: 10.230.70.1 #replace eip here
  disable: false
EOF
deployment.apps/kuard-deployment created
service/kuard-service created
eip.network.kubesphere.io/eip-kuard created
```
`kubectl get svc`
```
NAME            TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)   AGE
kuard-service   ClusterIP   10.32.0.186   <none>        80/TCP    6s
kubernetes      ClusterIP   10.32.0.1     <none>        443/TCP   7d4h
```
From within the cluster:
```
url 10.32.0.186
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">

  <title>KUAR Demo</title>

  <link rel="stylesheet" href="/static/css/bootstrap.min.css">
  <link rel="stylesheet" href="/static/css/styles.css">

  <script>
var pageContext = {"hostname":"kuard-deployment-75b548fd86-mp2bl","addrs":["10.0.5.146"],"version":"v0.8.1-1","versionColor":"hsl(18,100%,50%)","requestDump":"GET / HTTP/1.1\r\nHost: 10.32.0.186\r\nAccept: */*\r\nUser-Agent: curl/7.58.0","requestProto":"HTTP/1.1","requestAddr":"10.0.1.1:42144"}
  </script>
</head>
...
```

```
kubectl get all -n porter-system
NAME                       READY   STATUS    RESTARTS   AGE
pod/controller-manager-0   2/2     Running   0          70m
pod/porter-agent-d5sx9     1/1     Running   0          70m
pod/porter-agent-mmqp6     1/1     Running   0          70m
pod/porter-agent-qjzzj     1/1     Running   0          70m


NAME                                         TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)    AGE
service/controller-manager-metrics-service   ClusterIP   10.32.0.134   <none>        8443/TCP   70m
service/controller-manager-service           ClusterIP   10.32.0.34    <none>        443/TCP    70m

NAME                          DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/porter-agent   3         3         3       3            3           <none>          70m



NAME                                  READY   AGE
statefulset.apps/controller-manager   1/1     70m
```
